project:
  type: book

book:
  title: 'Sustainable Inference'
  subtitle: 'A Guide to Our System and Products'
  navbar:
    logo: images/logo.svg
    left:
      - href: index.qmd
        text: Home
      # - href: guidebook.qmd
      #   text: Guidebook
      # - href: Store
      #   text: store.qmd
      # - href: newsletter.qmd
        # text: Newsletter

format:
  html:
    theme:
      - cosmo
      - brand
      - styles.scss
    toc: true



